[package]
name = "world_automation"
edition = "2024.beta"

[dependencies]
world = { local = "../world" }
world_action_queue = { local = "../world_action_queue" }

[environments]
testnet_internal = "4c78adac"
testnet_utopia = "4c78adac"
testnet_stillness = "4c78adac"
